<?php

namespace Database\Seeders;

use App\Models\Spruch;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpruecheSeeder extends Seeder
{
    /**
     * 500 freche Sprüche nach Kategorie (100 pro Kategorie)
     */
    private array $sprueche = [
        'morgen' => [
            // Originale 10
            "Guten Morgen %s! Zeit, die Welt zu erobern... oder zumindest die Buchhaltung.",
            "Moin %s! Der frühe Vogel fängt den Wurm. Du fängst Rechnungen.",
            "Aufgewacht, %s! Die Rechnungen warten nicht von alleine.",
            "Guten Morgen %s! Kaffee ist fertig, Chaos auch.",
            "Hey %s, schon wach? Die Mahnungen vermissen dich!",
            "Buongiorno %s! Heute wird abgerechnet!",
            "Morgen %s! Lass uns Geld verdienen... oder zumindest einfordern.",
            "Guten Morgen %s, du alter Arbeitstier!",
            "Rise and shine, %s! Die Zahlen rufen!",
            "Na %s, ausgeschlafen? Dann mal ran an die Buletten!",
            // Neue 90
            "Guten Morgen %s! Der Kaffee ist stark, du hoffentlich auch.",
            "Hey %s, aufstehen! Das Geld verdient sich nicht von alleine.",
            "Buongiorno %s! Möge die Macht der Buchhaltung mit dir sein.",
            "Morgen %s! Heute schon über Mahngebühren nachgedacht?",
            "%s ist wach! Die Konkurrenz zittert bereits.",
            "Guten Morgen %s! Erst Kaffee, dann Weltherrschaft.",
            "Hey %s, die Sonne scheint, die Rechnungen auch nicht von alleine!",
            "Aufgewacht %s! Zeit für produktive Prokrastination.",
            "Moin %s! Heute wird durchgerechnet, nicht durchgedreht.",
            "Guten Morgen %s! Dein Schreibtisch hat dich vermisst. Wirklich.",
            "Hey %s, bereit für einen weiteren Tag im Paradies der Zahlen?",
            "Morgen %s! Die Excel-Tabellen freuen sich schon auf dich.",
            "Buongiorno %s! Kaffee trinken, Rechnungen schreiben, Welt retten.",
            "Guten Morgen %s! Mögen deine Kunden pünktlich zahlen.",
            "%s, aufwachen! Die Deadline wartet nicht.",
            "Hey %s, schon Kaffee intus? Gut, dann kann's losgehen!",
            "Morgen %s! Heute ist ein guter Tag zum Geld eintreiben.",
            "Guten Morgen %s! Deine To-Do-Liste weint schon.",
            "Moin Moin %s! Zeit für den täglichen Wahnsinn.",
            "Hey %s, früh übt sich, wer ein Meister der Mahnungen werden will!",
            "Buongiorno %s! Der frühe Buchhalter fängt den säumigen Zahler.",
            "Guten Morgen %s! Kaffee ist keine Frage, sondern die Antwort.",
            "Aufstehen %s! Die Zahlen sortieren sich nicht von selbst.",
            "Morgen %s! Ein neuer Tag, neue Rechnungen, gleiches Chaos.",
            "%s erwacht! Die Tabellenkalkulation jubelt.",
            "Hey %s, ausgeschlafen? Perfekt, die Arbeit ist hellwach!",
            "Guten Morgen %s! Heute: Kaffee, Chaos, Kontrolle.",
            "Moin %s! Der Drucker hat Papier, du hast Motivation. Oder?",
            "Buongiorno %s! Lass uns die Rechnungswelt rocken!",
            "Morgen %s! Erst mal einen Espresso, dann die Welt.",
            "Hey %s, bereit für Abenteuer zwischen Soll und Haben?",
            "Guten Morgen %s! Die Kaffeemaschine glüht schon.",
            "Aufgewacht %s! Zeit, Geld zu bewegen... auf dein Konto.",
            "Moin %s! Heute wird gerechnet, nicht geträumt!",
            "%s ist da! Die Aktenordner stehen stramm.",
            "Guten Morgen %s! Möge dein Kaffee stark und deine Kunden zahlungsfähig sein.",
            "Hey %s, der frühe Vogel... ach, du weißt schon!",
            "Buongiorno %s! Ein Cappuccino und los geht's!",
            "Morgen %s! Die Zahlen warten auf deinen Genius.",
            "Guten Morgen %s! Heute: weniger Drama, mehr Buchhaltung.",
            "Moin %s! Kaffee geladen, Motivation... wird noch gesucht.",
            "Hey %s, aufgestanden ist noch nicht aufgegeben!",
            "Guten Morgen %s! Der Tag ist jung, die Arbeit alt.",
            "Buongiorno %s! Cornetto und dann ab ans Werk!",
            "Morgen %s! Zeit, den inneren Buchhalter zu wecken.",
            "%s meldet sich zum Dienst! Die Rechnungen salutieren.",
            "Hey %s, noch müde? Ein Blick auf offene Rechnungen hilft!",
            "Guten Morgen %s! Heute wird Geld eingetrieben, nicht Schafe.",
            "Moin %s! Die Tastatur wartet auf deine Finger.",
            "Aufwachen %s! Der Kontostand verbessert sich nicht im Schlaf.",
            "Buongiorno %s! Pronto per lavorare? Hoffe ich doch!",
            "Morgen %s! Ein frischer Tag für frische Mahnungen.",
            "Hey %s, Kaffee Nummer eins oder schon Nummer drei?",
            "Guten Morgen %s! Die Zahlen haben dich vermisst.",
            "Moin %s! Heute: Rechnungen raus, Geld rein. Einfach, oder?",
            "Buongiorno %s! Der Espresso ist stark wie deine Entschlossenheit.",
            "%s startet durch! Die Buchhaltung macht sich bereit.",
            "Hey %s, gut geschlafen? Die Arbeit leider auch.",
            "Guten Morgen %s! Mögen alle Überweisungen eingehen.",
            "Morgen %s! Frühstück für Champions: Kaffee und Kontoauszüge.",
            "Moin %s! Die frühe Mahnung erreicht den säumigen Zahler.",
            "Aufgestanden %s! Zeit für Taten, nicht für Träume.",
            "Buongiorno %s! Oggi si lavora! Und wie!",
            "Hey %s, der Morgen gehört dir. Die Rechnungen auch.",
            "Guten Morgen %s! Dein Posteingang platzt vor Vorfreude.",
            "Morgen %s! Neuer Tag, neues Glück, alte Schulden.",
            "%s ist online! Die Datenbank jubiliert.",
            "Moin %s! Zeit, den Kaffee zur Waffe zu machen.",
            "Guten Morgen %s! Heute: Operation Zahlungseingang.",
            "Hey %s, aufgewacht mit dem Drang zu buchhalten?",
            "Buongiorno %s! La vita è bella, die Arbeit auch. Manchmal.",
            "Morgen %s! Die Frühschicht der Fleißigen beginnt.",
            "Guten Morgen %s! Kaffee, Computer, Kalkulieren!",
            "Moin %s! Der Tagesanbruch der Tabellenkalkulation.",
            "Hey %s, früh dran heute! Die Akten applaudieren.",
            "Aufgewacht %s! Schlaf ist für die Schwachen. Und das Wochenende.",
            "Buongiorno %s! Pronto? Pronti? Via!",
            "Morgen %s! Ein Lächeln, ein Kaffee, ein Haufen Arbeit.",
            "Guten Morgen %s! Die Welt wartet auf deine Rechnungen.",
            "Hey %s, motiviert? Nein? Kaffee hilft!",
            "%s beginnt den Tag! Die Zahlen zittern vor Respekt.",
            "Moin %s! Heute: Buchungen, Buchungen, Buchungen!",
            "Guten Morgen %s! Auf in den Kampf gegen die Papierberge!",
            "Buongiorno %s! Der Morgen ist zum Arbeiten da. Leider.",
            "Hey %s, schon wach? Dann mal los, die Zeit rennt!",
            "Morgen %s! Ein Tag ohne Rechnung ist ein verlorener Tag.",
            "Guten Morgen %s! Dein Konto freut sich auf Zuwachs.",
            "Moin %s! Die Kaffeemaschine ist dein bester Freund.",
            "Aufwachen %s! Die Buchhaltung ruft nach ihrem Helden.",
            "Hey %s, heute schon einen Zahlungseingang geträumt?",
            "Buongiorno %s! Caffè e fatture – la combinazione perfetta!",
        ],
        'mittag' => [
            // Originale 10
            "Mahlzeit %s! Schon was geschafft heute?",
            "Hey %s, Mittagspause vorbei? Weiter geht's!",
            "Hallo %s! Die Hälfte ist geschafft... oder auch nicht.",
            "Na %s, schon hungrig? Die Rechnungen sind es auch!",
            "Buon pranzo %s! Nach dem Essen wird weitergearbeitet!",
            "%s, du Held! Halte durch, bald ist Feierabend!",
            "Ciao %s! Noch ein paar Stunden, dann ist Ruhe.",
            "Hey %s, wie läuft's? Chaos oder nur Durcheinander?",
            "Hallo %s! Zeit für den Endspurt!",
            "Na %s, noch motiviert? Fake it till you make it!",
            // Neue 90
            "Mahlzeit %s! Hoffentlich war das Essen besser als die Zahlen.",
            "Hey %s, Mittagstief? Ein Espresso und weiter geht's!",
            "Hallo %s! Die zweite Halbzeit hat begonnen.",
            "%s, schon Pasta gehabt? Perfekte Energie für Rechnungen!",
            "Buon appetito %s! Danach wird wieder geschuftet.",
            "Na %s, gut gegessen? Die Arbeit hat auch Hunger!",
            "Hey %s, Mittagspause ist vorbei. Zurück an die Front!",
            "Mahlzeit %s! Der Nachmittag wird dein Freund. Vielleicht.",
            "Ciao %s! Noch vier Stunden bis zur Freiheit!",
            "%s, halte durch! Das Feierabendbier wartet.",
            "Hey %s, schon die Hälfte rum! Glas halb voll, oder?",
            "Hallo %s! Mittagsschlaf ist leider nicht drin.",
            "Na %s, wie steht's? Die Rechnungen vermehren sich!",
            "Buon pomeriggio %s! Weiter, immer weiter!",
            "Mahlzeit %s! Energie tanken und dann: Endspurt!",
            "Hey %s, der Kaffee nach dem Essen ist Pflicht!",
            "%s, du schaffst das! Noch ein paar Stunden!",
            "Hallo %s! Die Nachmittags-Schicht beginnt.",
            "Na %s, Mittagstief überwunden? Sehr gut!",
            "Ciao %s! La dolce vita muss warten, erst die Arbeit.",
            "Hey %s, schon satt? Gut, dann kann's weitergehen!",
            "Mahlzeit %s! Der Schreibtisch wartet ungeduldig.",
            "%s, Halbzeit! Jetzt noch mal Gas geben!",
            "Buon pranzo %s! Ein voller Bauch arbeitet nicht gern... muss aber!",
            "Hallo %s! Die Mittagsruhe ist vorbei, der Kampf geht weiter.",
            "Na %s, gestärkt? Die Rechnungen auch!",
            "Hey %s, Nachmittagsprogramm: Rechnungen, Mahnungen, Wahnsinn.",
            "Mahlzeit %s! Hoffentlich nichts Schweres gegessen.",
            "%s, weiter geht's! Der Feierabend rückt näher.",
            "Ciao %s! Forza, nur noch ein bisschen!",
            "Hallo %s! Nach dem Essen sollst du ruhn... aber nicht heute!",
            "Hey %s, Mittagessen verdaut? Perfekt, ran an die Arbeit!",
            "Na %s, wie war das Menü? Egal, die Zahlen warten!",
            "Buon pomeriggio %s! Zeit für produktive Stunden.",
            "Mahlzeit %s! Der Nachmittag gehört den Fleißigen.",
            "%s, der Countdown läuft! Noch ein paar Stunden.",
            "Hallo %s! Kaffee Nummer zwei, drei, vier?",
            "Hey %s, Mittagstief? Kenn ich nicht, hab ich nicht!",
            "Na %s, die Uhr tickt, die Arbeit wartet!",
            "Ciao %s! Avanti, avanti! Weiter geht's!",
            "Mahlzeit %s! Jetzt aber keine Müdigkeit vorschützen!",
            "%s, halte durch! Du bist fast... na ja, auf halbem Weg.",
            "Buon pranzo %s! Adesso si lavora sul serio!",
            "Hey %s, Energie getankt? Wunderbar, du wirst sie brauchen!",
            "Hallo %s! Die Post-Mittagszeit ist Buchhalterzeit.",
            "Na %s, bereit für Runde zwei? Ding ding!",
            "Mahlzeit %s! Der Schreibtisch ruft. Leider.",
            "%s, du machst das super! Oder zumindest akzeptabel.",
            "Ciao %s! Ein Döner, ein Espresso, und weiter!",
            "Hey %s, das Mittagstief ist für Anfänger!",
            "Buon appetito %s! Schnell essen, schnell arbeiten!",
            "Hallo %s! Der Nachmittag wird intensiv. Wie immer.",
            "Na %s, schon motiviert für die zweite Hälfte?",
            "Mahlzeit %s! Kurze Pause, langer Nachmittag.",
            "%s, durchhalten! Das Wochenende kommt. Irgendwann.",
            "Hey %s, Mittagessen war hoffentlich kein Schnitzelkoma!",
            "Ciao %s! Pranzo finito, lavoro infinito!",
            "Hallo %s! Nur noch vier Stunden. Oder fünf. Oder sechs...",
            "Na %s, alles im grünen Bereich? Zumindest farblich?",
            "Buon pomeriggio %s! Coraggio, ce la fai!",
            "Mahlzeit %s! Der Körper ist satt, der Geist ist willig.",
            "Hey %s, Nachmittagsblues? Nicht mit uns!",
            "%s, die Sonne scheint, die Rechnungen stapeln sich!",
            "Hallo %s! Kaffee kalt? Arbeit heiß? Perfekt!",
            "Na %s, schon wieder am Schreibtisch? Tapfer!",
            "Ciao %s! Ancora un po' di pazienza!",
            "Mahlzeit %s! Schnell essen, langsam arbeiten... nein, andersrum!",
            "Hey %s, der Nachmittag ist jung, die Arbeit alt!",
            "Buon pranzo %s! Energia per il pomeriggio!",
            "%s, halte durch! Der Kühlschrank mit dem Bier wartet!",
            "Hallo %s! Mittagspause war gestern. Oder vor einer Stunde.",
            "Na %s, schon den Überblick verloren? Normal!",
            "Mahlzeit %s! Der Nachmittag ist dein Freund. Theoretisch.",
            "Ciao %s! Nur Mut, bald ist es geschafft!",
            "Hey %s, das Mittagstief besiegen wir gemeinsam!",
            "Buon pomeriggio %s! Ora si fa sul serio!",
            "Hallo %s! Der Countdown zum Feierabend läuft.",
            "%s, weiter so! Die Zahlen brauchen dich!",
            "Na %s, schon alle Rechnungen geschrieben? Nein? Na dann!",
            "Mahlzeit %s! Ein voller Bauch, ein voller Terminkalender.",
            "Hey %s, Nachmittagsprogramm: überleben und abrechnen!",
            "Ciao %s! La pausa pranzo è finita, purtroppo.",
            "Hallo %s! Die Arbeit ruft, und sie ist ziemlich laut!",
            "Buon pranzo %s! Jetzt aber zurück an die Tastatur!",
            "%s, du schaffst das! Positiv denken, negativ buchen!",
            "Na %s, bereit für den Endspurt? Fast jedenfalls!",
            "Mahlzeit %s! Der Nachmittag wartet auf deinen Einsatz.",
            "Hey %s, Energie aus dem Essen nutzen – jetzt oder nie!",
            "Ciao %s! Avanti popolo, zur Arbeit!",
            "Hallo %s! Noch ein paar produktive Stunden, versprochen!",
            "Buon pomeriggio %s! Forza e coraggio!",
            "%s, Mittagstief? Kaffee! Noch mehr Kaffee!",
            "Na %s, der Schreibtisch hat dich vermisst. Nicht.",
            "Mahlzeit %s! Zeit, die Ärmel hochzukrempeln!",
            "Hey %s, halbe Strecke geschafft! Nur noch 50 Prozent!",
        ],
        'abend' => [
            // Originale 10
            "Guten Abend %s! Immer noch hier? Respekt!",
            "Hey %s, Überstunden? Die Rechnungen danken es dir!",
            "Buonasera %s! Feierabend ist überbewertet, oder?",
            "Na %s, du Workaholic! Ab nach Hause!",
            "Hallo %s! Die Arbeit läuft nicht weg... leider.",
            "%s, immer noch da? Die Familie vermisst dich!",
            "Abend %s! Morgen ist auch noch ein Tag.",
            "Hey %s, mach Schluss für heute! Du hast es verdient.",
            "Ciao %s! Genug gearbeitet, jetzt wird gelebt!",
            "Guten Abend %s! Zeit für ein Bier... oder zwei.",
            // Neue 90
            "Buonasera %s! Noch hier? Du bist ja hartnäckig!",
            "Hey %s, die Sonne geht unter, du immer noch nicht?",
            "Guten Abend %s! Der Feierabend ruft. Hörst du ihn?",
            "%s, Überstunden sammeln? Du bist ein Profi!",
            "Abend %s! Das Sofa weint ohne dich.",
            "Na %s, noch am Rechnen? Die Zahlen schlafen auch bald.",
            "Ciao %s! Basta lavorare, adesso si riposa!",
            "Hey %s, der Monitor ist müde. Du etwa nicht?",
            "Guten Abend %s! Die Rechnungen können warten. Theoretisch.",
            "Buonasera %s! Aperitivo-Zeit, nicht Arbeitszeit!",
            "%s, immer noch am Kämpfen? Respekt und Mitleid!",
            "Abend %s! Zeit, die Waffen zu strecken.",
            "Hey %s, Feierabend ist ein Grundrecht. Nutze es!",
            "Na %s, schon dunkel draußen. Und du noch drin!",
            "Guten Abend %s! Das Bett vermisst dich bestimmt.",
            "Ciao %s! Lavoro finito? Oder noch nicht?",
            "Buonasera %s! Ein Spritz und dann Feierabend?",
            "%s, du bist ja immer noch hier! Wahnsinn!",
            "Hey %s, der Abend ist zum Entspannen da. Eigentlich.",
            "Abend %s! Die To-Do-Liste kann auch morgen weinen.",
            "Guten Abend %s! Genug ist genug. Manchmal jedenfalls.",
            "Na %s, die Kerze brennt an beiden Enden, was?",
            "Ciao %s! Ora basta, anche le fatture hanno bisogno di dormire!",
            "Buonasera %s! Pizza bestellen und Feierabend?",
            "Hey %s, Workaholic des Tages! Glückwunsch... glaube ich.",
            "%s, Überstunden-König! Oder Königin!",
            "Abend %s! Der Kühlschrank zu Hause ist auch einsam.",
            "Guten Abend %s! Morgen ist ein neuer Tag voller Chaos.",
            "Na %s, schon Pläne für den Feierabend? Falls er kommt?",
            "Ciao %s! La giornata è finita, goditi la serata!",
            "Hey %s, die Tastatur hat auch mal Pause verdient!",
            "Buonasera %s! Quanto ancora? Genug!",
            "%s, Feierabend bedeutet: aufhören. Jetzt.",
            "Abend %s! Der Tag war lang, die Nacht ist kurz.",
            "Guten Abend %s! Netflix wartet, die Arbeit nicht.",
            "Na %s, noch ein letzter Blick auf die Zahlen?",
            "Hey %s, ab nach Hause! Befehl von oben. Also von mir.",
            "Ciao %s! È ora di staccare la spina!",
            "Buonasera %s! Ein Gläschen Wein als Belohnung?",
            "%s, genug gearbeitet! Der Feierabend beginnt... jetzt!",
            "Abend %s! Die Arbeit ist erledigt. Mehr oder weniger.",
            "Guten Abend %s! Zeit für den wohlverdienten Feierabend.",
            "Na %s, noch nicht müde? Bewundernswert... oder besorgniserregend.",
            "Hey %s, pack die Sachen! Morgen ist auch noch ein Tag.",
            "Ciao %s! Addio lavoro, benvenuto relax!",
            "Buonasera %s! Die Rechnungen werden morgen auch noch da sein.",
            "%s, Schluss jetzt! Das ist ein Befehl.",
            "Abend %s! Zeit für etwas anderes als Zahlen.",
            "Guten Abend %s! Die Bürostühle brauchen auch mal Ruhe.",
            "Na %s, immer noch am Schreibtisch? Du bist verrückt. Aber gut.",
            "Hey %s, Feierabend! Das ist keine Bitte.",
            "Ciao %s! Fine della giornata lavorativa!",
            "Buonasera %s! Der Aperitivo wartet nicht ewig!",
            "%s, ab auf die Couch! Die Rechnungen laufen nicht weg.",
            "Abend %s! Zeit, abzuschalten. Buchstäblich.",
            "Guten Abend %s! Die Arbeit ist geschafft... größtenteils.",
            "Na %s, genug für heute! Oder für diese Woche.",
            "Hey %s, der Feierabend ruft lauter als die Mahnungen!",
            "Ciao %s! Tempo di andare a casa!",
            "Buonasera %s! Heute Abend: kein Stress, nur Entspannung.",
            "%s, weg vom Schreibtisch! Sofort!",
            "Abend %s! Die Zahlen werden dich morgen wieder begrüßen.",
            "Guten Abend %s! Zeit für ein Leben außerhalb der Arbeit.",
            "Na %s, Überstunden hin oder her, jetzt ist Schluss!",
            "Hey %s, Feierabend ist heilig. Behandle ihn so!",
            "Ciao %s! A domani, caro lavoro!",
            "Buonasera %s! Der Abend gehört dir, nicht den Rechnungen.",
            "%s, genug gerechnet! Zeit zum Abschalten.",
            "Abend %s! Laptop zu, Feierabend an!",
            "Guten Abend %s! Das Sofa ruft deinen Namen.",
            "Na %s, letzter Check und dann ab die Post!",
            "Hey %s, der Tag war lang genug. Feierabend!",
            "Ciao %s! Il lavoro può aspettare fino a domani!",
            "Buonasera %s! Zeit für ein bisschen dolce vita!",
            "%s, Feierabend! Keine Diskussion!",
            "Abend %s! Morgen kämpfen wir weiter. Heute: Pause!",
            "Guten Abend %s! Weg mit der Arbeit, her mit dem Wein!",
            "Na %s, tapfer durchgehalten! Jetzt: Belohnung!",
            "Hey %s, die Arbeit ist erledigt. Zumindest ein Teil davon.",
            "Ciao %s! Buona serata e riposati!",
            "Buonasera %s! Schluss, aus, Feierabend!",
            "%s, genug! Der Feierabend hat dich verdient.",
            "Abend %s! Zeit, die Batterien aufzuladen.",
            "Guten Abend %s! Arbeit gut, alles gut. Jetzt: Feierabend!",
            "Na %s, noch hier? Respekt... aber geh jetzt!",
            "Hey %s, der Tag ist vorbei. Feier ihn!",
            "Ciao %s! La serata ti aspetta!",
            "Buonasera %s! Genug der Zahlen, her mit dem Vergnügen!",
            "%s, du hast es geschafft! Feierabend, Champion!",
        ],
        'nacht' => [
            // Originale 10
            "Hey %s, kannst du nicht schlafen? Ich auch nicht.",
            "Nachtschicht, %s? Du bist verrückt. Aber sympathisch.",
            "%s um diese Uhrzeit? Hardcore!",
            "Buonanotte %s! Oder doch nicht?",
            "Hey %s, die Geister der unbezahlten Rechnungen grüßen!",
            "Na %s, Insomnia oder Deadline?",
            "Hallo %s, du Nachteule! Schlaf ist was für Schwache.",
            "%s arbeitet nachts? Legend!",
            "Hey %s, die Server schlafen nie. Du anscheinend auch nicht.",
            "Gute Nacht %s! Oh wait, du arbeitest ja noch...",
            // Neue 90
            "Hey %s, mitten in der Nacht? Du bist ein Tier!",
            "Buonanotte %s! Die Sterne gucken zu. Und die Rechnungen.",
            "%s, Nachtschicht? Die Ruhe ist perfekt zum Arbeiten.",
            "Na %s, die ganze Welt schläft. Außer dir.",
            "Hey %s, Vampir oder Buchhalter? Beides anscheinend!",
            "Gute Nacht... ach nein, du arbeitest ja, %s!",
            "%s um diese Uhrzeit online? Respekt und Wahnsinn!",
            "Buonanotte %s! Ma che fai ancora qui?",
            "Hey %s, die Eulen sind neidisch auf dich!",
            "Na %s, Schlafstörung oder Arbeitswut?",
            "%s, Nachts sind alle Zahlen schwarz. Oder rot.",
            "Hallo %s, du Nachtarbeiter! Die Dunkelheit grüßt.",
            "Hey %s, kein Bett in Sicht? Nur der Schreibtisch?",
            "Buonanotte %s! Le fatture non dormono, tu nemmeno!",
            "Na %s, stille Nacht, heilige... Arbeit?",
            "%s, die Nacht ist jung. Du hoffentlich nicht mehr.",
            "Hey %s, Nachtschicht-Held im Einsatz!",
            "Gute Nacht %s! Oder guten Morgen? Egal, du arbeitest.",
            "Na %s, die Welt träumt, du rechnest.",
            "Buonanotte %s! La notte porta consiglio... e lavoro!",
            "%s ist wach! Die Nacht zittert vor Respekt.",
            "Hey %s, Kaffee um Mitternacht? Klassiker!",
            "Hallo %s, die Geister der Buchhaltung grüßen!",
            "Na %s, Deadline oder einfach nur verrückt?",
            "Buonanotte %s! Ancora sveglio? Che dedizione!",
            "%s, Nachtarbeiter des Jahres! Die Auszeichnung ist unterwegs.",
            "Hey %s, Schlafen ist überbewertet, oder?",
            "Gute Nacht %s! Die Rechnungen schlafen nie, du auch nicht.",
            "Na %s, die Nacht gehört den Mutigen. Und den Wahnsinnigen.",
            "Buonanotte %s! La luna ti fa compagnia!",
            "%s arbeitet, während andere träumen. Held!",
            "Hey %s, nächtliche Produktivität ist die beste!",
            "Hallo %s, Nachteule im Dienst!",
            "Na %s, Kaffee kalt, Augen müde, Geist stark?",
            "Buonanotte %s! Che notte lunga, eh?",
            "%s, die Sterne leuchten für dich. Und deine Rechnungen.",
            "Hey %s, Schlaf ist für Anfänger!",
            "Gute Nacht %s! Ach ne, du bist ja wach.",
            "Na %s, noch ein paar Stunden bis Sonnenaufgang!",
            "Buonanotte %s! Ma perché non dormi?",
            "%s ist online! Die Nacht ist produktiv.",
            "Hey %s, Mitternachts-Buchhalter klingt wie ein Superheld!",
            "Hallo %s, die Dunkelheit ist dein Freund. Und die Arbeit.",
            "Na %s, nächtliches Chaos oder nächtliche Ordnung?",
            "Buonanotte %s! Le stelle brillano, tu lavori!",
            "%s, wer braucht schon Schlaf? Du offensichtlich nicht.",
            "Hey %s, die Nacht ist still. Perfekt zum Konzentrieren!",
            "Gute Nacht %s! Ups, du machst ja noch nicht Schluss.",
            "Na %s, Nachtmensch durch und durch!",
            "Buonanotte %s! Lavorare di notte ha il suo fascino!",
            "%s, nächtliche Abenteuer in der Buchhaltung!",
            "Hey %s, die Uhr tickt, aber du tickst nicht aus.",
            "Hallo %s, Willkommen in der Nachtschicht-Elite!",
            "Na %s, Mond und Rechnungen – romantisch, oder?",
            "Buonanotte %s! La notte è lunga, ma tu sei forte!",
            "%s arbeitet, die Welt schläft. So muss das!",
            "Hey %s, Kaffee Nummer... ach, wer zählt schon?",
            "Gute Nacht %s! Die Arbeit ist wach, du auch.",
            "Na %s, nächtliche Inspiration bei den Zahlen?",
            "Buonanotte %s! Ancora qualche fattura e poi a letto!",
            "%s, Schlafentzug ist der beste Antrieb. Oder so.",
            "Hey %s, die Stille der Nacht fördert die Produktivität!",
            "Hallo %s, du Krieger der Nacht!",
            "Na %s, bald geht die Sonne auf. Du arbeitest noch.",
            "Buonanotte %s! Il lavoro notturno è per i veri eroi!",
            "%s ist noch da! Die Nacht verneigt sich.",
            "Hey %s, Morgenstund hat Gold... aber Nachtarbeit auch!",
            "Gute Nacht %s! Oder guten Arbeitswahn!",
            "Na %s, die Eulen fragen sich, was du da tust.",
            "Buonanotte %s! Forza, ancora un po'!",
            "%s, nächtlicher Buchhalter im Einsatz. Held!",
            "Hey %s, der Mond ist dein Zeuge. Du arbeitest!",
            "Hallo %s, Willkommen in der Welt der Schlaflosen!",
            "Na %s, Koffein und Kalkulation – die Nachtformel!",
            "Buonanotte %s! Dormi mai? Chiaramente no!",
            "%s, die Nacht gehört dir. Und den Mahnungen.",
            "Hey %s, nachts sind alle Buchhalter... wach?",
            "Gute Nacht %s! Die Arbeit schläft nie, du auch nicht.",
            "Na %s, noch wach? Du bist offiziell verrückt. Glückwunsch!",
            "Buonanotte %s! Un altro caffè e si continua!",
            "%s arbeitet, während die Welt träumt. Legende!",
            "Hey %s, nächtliche Stille, perfekt für Rechnungen!",
            "Hallo %s, die Nacht ist jung, die Arbeit endlos!",
            "Na %s, Schlaf wird überbewertet. Von Losern.",
            "Buonanotte %s! Le fatture ringraziano la tua dedizione!",
            "%s, du bist der Herrscher der Nacht!",
            "Hey %s, bald ist Frühstück. Vorher noch arbeiten?",
            "Gute Nacht %s! Die Zahlen sind auch noch wach.",
            "Na %s, Nachtschicht-Champion am Start!",
        ],
        'wochenende' => [
            // Originale 10
            "Wochenende %s? Was machst du hier?!",
            "Hey %s, selbst am Wochenende? Du brauchst ein Hobby!",
            "%s am Samstag/Sonntag? Respekt... oder Mitleid?",
            "Buon fine settimana %s! Aber offensichtlich nicht für dich.",
            "Hallo %s! Familie? Freunde? Nein? OK, dann arbeite mal.",
            "Hey %s, Wochenende ist zum Erholen da... theoretisch.",
            "%s, du Streber! Wenigstens einer arbeitet hier.",
            "Na %s, die Rechnungen warten nicht aufs Wochenende!",
            "Hey %s, du weißt schon, dass heute frei ist?",
            "Ciao %s! Selbst Workaholics brauchen mal Pause!",
            // Neue 90
            "Wochenende %s! Andere grillen, du arbeitest. Klassiker!",
            "Hey %s, Samstag oder Sonntag? Egal, du bist hier!",
            "Buon weekend %s! Ma che ci fai in ufficio?",
            "%s am Wochenende online? Du bist unverbesserlich!",
            "Hallo %s! Die Welt entspannt, du rechnest.",
            "Na %s, Wochenende ist doch nur ein Wort, oder?",
            "Hey %s, hast du kein Zuhause? Oder keine Ruhe?",
            "Ciao %s! Il weekend è fatto per riposare... in teoria!",
            "%s, Wochenend-Krieger im Einsatz!",
            "Buon fine settimana %s! Anche se lavori!",
            "Hey %s, während andere brunchen, rechnest du!",
            "Wochenende %s! Die Rechnungen kennen keinen Ruhetag.",
            "Na %s, Workaholic-Status bestätigt!",
            "Hallo %s! Das Sofa weint, der Schreibtisch lacht.",
            "Ciao %s! Lavorare nel weekend? Che dedizione!",
            "%s am Wochenende? Dein Einsatz ist legendär!",
            "Hey %s, Freizeit ist was für Anfänger!",
            "Buon weekend %s! Lavoro o passione? Beides!",
            "Na %s, der Strand wartet... aber nicht auf dich.",
            "Wochenende %s! Andere feiern, du buchst.",
            "Hallo %s! Samstag, Sonntag, Arbeitstag – alles eins!",
            "Hey %s, Wochenend-Held am Schreibtisch!",
            "Ciao %s! Nemmeno il weekend ti ferma!",
            "%s, du kennst kein Wochenende. Nur Arbeit.",
            "Buon fine settimana %s! Almeno prendi un caffè!",
            "Na %s, während alle grillen, grillst du Zahlen!",
            "Wochenende %s! Die Rechnungen haben auch frei... eigentlich.",
            "Hey %s, Sonntagsarbeit ist die beste Arbeit! Nicht.",
            "Hallo %s! Das Wochenende ist überbewertet, sagt keiner.",
            "Ciao %s! Weekend? Mai sentito!",
            "%s am Wochenende? Du definierst Arbeitsmoral neu!",
            "Buon weekend %s! Lavori sempre, vero?",
            "Na %s, Samstagsarbeit für Fortgeschrittene!",
            "Hey %s, dein Wochenende: Rechnungen statt Relaxen!",
            "Wochenende %s! Die Zahlen ruhen nie, du auch nicht.",
            "Hallo %s! Frei ist nur ein Konzept, das du ignorierst.",
            "Ciao %s! Il weekend è un optional per te!",
            "%s, Wochenendarbeit ist auch Arbeit. Nur schlimmer.",
            "Buon fine settimana %s! Ma riposa ogni tanto!",
            "Na %s, das Wochenende sieht dich arbeiten. Wie immer.",
            "Hey %s, Sonnenschein draußen, Arbeit drinnen!",
            "Wochenende %s! Die Familie weiß, wo du bist: hier!",
            "Hallo %s! Samstag ist der neue Montag, oder?",
            "Ciao %s! Weekendlavoratore professionista!",
            "%s am Wochenende online? Verrückt, aber respektabel!",
            "Buon weekend %s! Almeno mangia qualcosa!",
            "Na %s, Wochenende bedeutet für dich: Weiter arbeiten!",
            "Hey %s, andere haben Hobbys, du hast Rechnungen!",
            "Wochenende %s! Der Schreibtisch freut sich, dich zu sehen.",
            "Hallo %s! Ruhetag? Kenn ich nicht, hab ich nicht.",
            "Ciao %s! Anche di weekend, sempre sul pezzo!",
            "%s, das Wochenende ist nur eine Pause... für andere.",
            "Buon fine settimana %s! Lavorare è la tua passione!",
            "Na %s, während alle ausschlafen, arbeitest du!",
            "Hey %s, Wochenendarbeit: 10 von 10 Punkten für Einsatz!",
            "Wochenende %s! Die Sonne scheint, die Arbeit auch!",
            "Hallo %s! Kein freier Tag ohne freie Rechnungen!",
            "Ciao %s! Il weekend non esiste per te, vero?",
            "%s am Wochenende? Du bist offiziell süchtig nach Arbeit!",
            "Buon weekend %s! Prendi almeno un aperitivo!",
            "Na %s, Samstag, Sonntag – alles Arbeitstage!",
            "Hey %s, der Park ist voll, dein Büro auch: mit dir!",
            "Wochenende %s! Die Zahlen kennen keinen Samstag.",
            "Hallo %s! Freie Tage sind was für Weicheier!",
            "Ciao %s! Lavorare nel fine settimana? Normale!",
            "%s, Wochenendarbeit ist dein Cardio!",
            "Buon fine settimana %s! Ma ogni tanto stacca!",
            "Na %s, alle relaxen, du rotierst!",
            "Hey %s, Wochenende heißt: Woche und Ende... der Ruhe!",
            "Wochenende %s! Die Buchhaltung dankt für deinen Einsatz!",
            "Hallo %s! Samstagsarbeit, Sonntagsarbeit – alles eins!",
            "Ciao %s! Sei un vero stacanovista!",
            "%s am Wochenende? Du bist mein Held!",
            "Buon weekend %s! Lavoro anche oggi? Ovvio!",
            "Na %s, kein Wochenende ohne Arbeit, stimmt's?",
            "Hey %s, Freizeit ist ein Fremdwort für dich!",
            "Wochenende %s! Andere machen Party, du machst Buchhaltung.",
            "Hallo %s! Das Wochenende gehört den Fleißigen!",
            "Ciao %s! Lavori sempre, sei incredibile!",
            "%s, Wochenend-Workaholic in Action!",
            "Buon fine settimana %s! Non fermarti mai!",
            "Na %s, Wochenende ist für Amateure!",
            "Hey %s, während alle feiern, feierst du... Rechnungen!",
            "Wochenende %s! Die Arbeit ruft, du antwortest.",
            "Hallo %s! Samstag, Sonntag, egal – Hauptsache Arbeit!",
            "Ciao %s! Il fine settimana è sopravvalutato!",
            "%s am Wochenende online? Chapeau!",
            "Buon weekend %s! Sei sempre il primo!",
            "Na %s, das Wochenende sieht dich. Am Schreibtisch.",
            "Hey %s, Wochenendarbeit für Legenden!",
            "Wochenende %s! Du machst das Unmögliche möglich!",
            "Hallo %s! Arbeit am Wochenende? Standard für dich!",
            "Ciao %s! Lavori anche nel weekend! Rispetto!",
        ],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $inserted = 0;
        $skipped = 0;

        foreach ($this->sprueche as $kategorie => $texte) {
            foreach ($texte as $index => $text) {
                // Prüfen ob Spruch bereits existiert (nach Text und Kategorie)
                $exists = Spruch::where('kategorie', $kategorie)
                    ->where('text', $text)
                    ->exists();

                if ($exists) {
                    $skipped++;
                    continue;
                }

                Spruch::create([
                    'kategorie' => $kategorie,
                    'text' => $text,
                    'aktiv' => true,
                    'sort_order' => $index,
                ]);
                $inserted++;
            }
        }

        $this->command->info("✓ Sprüche-Seeder abgeschlossen:");
        $this->command->info("  - {$inserted} neue Sprüche eingefügt");
        $this->command->info("  - {$skipped} bereits vorhanden (übersprungen)");
        $this->command->info("  - " . Spruch::count() . " Sprüche insgesamt in der Datenbank");
    }
}
